# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 'y9Brhf6v'
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5673:5672"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080